
namespace WindowsFormsApp1
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.FlatScrollBarRenderer flatScrollBarRenderer1 = new FarPoint.Win.Spread.FlatScrollBarRenderer();
            FarPoint.Win.Spread.NamedStyle namedStyle1 = new FarPoint.Win.Spread.NamedStyle("BorderEx73638696207321638122");
            FarPoint.Win.ComplexBorder complexBorder1 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))))), new FarPoint.Win.ComplexBorderSide(System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))))), new FarPoint.Win.ComplexBorderSide(System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))))), new FarPoint.Win.ComplexBorderSide(System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))))), new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None), false, false);
            FarPoint.Win.Spread.NamedStyle namedStyle2 = new FarPoint.Win.Spread.NamedStyle("Color103638696207321648112");
            FarPoint.Win.Spread.NamedStyle namedStyle3 = new FarPoint.Win.Spread.NamedStyle("Font268638696207321678032");
            FarPoint.Win.Spread.TipAppearance tipAppearance1 = new FarPoint.Win.Spread.TipAppearance();
            FarPoint.Win.Spread.FlatScrollBarRenderer flatScrollBarRenderer2 = new FarPoint.Win.Spread.FlatScrollBarRenderer();
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenFocusedNormal;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenFocusedReadOnly;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenFocusedRowMode;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenFocusedSingleSelect;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenFocusedMultiSelect;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenFocusedExtendedSelect;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenAncestorOfFocusedNormal;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenAncestorOfFocusedReadOnly;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenAncestorOfFocusedRowMode;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect;
            FarPoint.Win.Spread.InputMap fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect;
            FarPoint.Win.ComplexBorder complexBorder2 = new FarPoint.Win.ComplexBorder(new FarPoint.Win.ComplexBorderSide(FarPoint.Win.ComplexBorderSideStyle.None));
            FarPoint.Win.Spread.CellType.TextCellType textCellType1 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType2 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType1 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType2 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType3 = new FarPoint.Win.Spread.CellType.TextCellType();
            this.button1 = new System.Windows.Forms.Button();
            this.fpSpread1 = new FarPoint.Win.Spread.FpSpread();
            this.fpSpread1_Sheet1 = new FarPoint.Win.Spread.SheetView();
            fpSpread1_InputMapWhenFocusedNormal = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedReadOnly = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedRowMode = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedSingleSelect = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedMultiSelect = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedExtendedSelect = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedNormal = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect = new FarPoint.Win.Spread.InputMap();
            ((System.ComponentModel.ISupportInitialize)(this.fpSpread1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.fpSpread1_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(12, 12);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(173, 23);
            this.button1.TabIndex = 1;
            this.button1.Text = "출력";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // fpSpread1
            // 
            this.fpSpread1.AccessibleDescription = "fpSpread1, Sheet1, Row 0, Column 0";
            this.fpSpread1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.fpSpread1.EditModeReplace = true;
            this.fpSpread1.HorizontalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.fpSpread1.HorizontalScrollBar.Name = "";
            flatScrollBarRenderer1.ArrowColor = System.Drawing.Color.FromArgb(((int)(((byte)(121)))), ((int)(((byte)(121)))), ((int)(((byte)(121)))));
            flatScrollBarRenderer1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            flatScrollBarRenderer1.BorderActiveColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            flatScrollBarRenderer1.TrackBarBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(219)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.fpSpread1.HorizontalScrollBar.Renderer = flatScrollBarRenderer1;
            this.fpSpread1.Location = new System.Drawing.Point(0, 67);
            this.fpSpread1.MessageBoxCaption = "Spread";
            this.fpSpread1.Name = "fpSpread1";
            namedStyle1.BackColor = System.Drawing.Color.Empty;
            namedStyle1.Border = complexBorder1;
            namedStyle1.ForeColor = System.Drawing.Color.Empty;
            namedStyle1.Locked = false;
            namedStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            namedStyle2.Border = complexBorder1;
            namedStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            namedStyle2.Locked = false;
            namedStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            namedStyle3.Border = complexBorder1;
            namedStyle3.Font = new System.Drawing.Font("굴림체", 9F);
            namedStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            namedStyle3.Locked = false;
            this.fpSpread1.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle1,
            namedStyle2,
            namedStyle3});
            this.fpSpread1.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.fpSpread1_Sheet1});
            this.fpSpread1.Size = new System.Drawing.Size(1359, 684);
            this.fpSpread1.TabIndex = 6;
            tipAppearance1.BackColor = System.Drawing.SystemColors.Info;
            tipAppearance1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            tipAppearance1.ForeColor = System.Drawing.SystemColors.InfoText;
            this.fpSpread1.TextTipAppearance = tipAppearance1;
            this.fpSpread1.VerticalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.fpSpread1.VerticalScrollBar.Name = "";
            flatScrollBarRenderer2.ArrowColor = System.Drawing.Color.FromArgb(((int)(((byte)(121)))), ((int)(((byte)(121)))), ((int)(((byte)(121)))));
            flatScrollBarRenderer2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            flatScrollBarRenderer2.BorderActiveColor = System.Drawing.Color.FromArgb(((int)(((byte)(171)))), ((int)(((byte)(171)))), ((int)(((byte)(171)))));
            flatScrollBarRenderer2.TrackBarBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(219)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.fpSpread1.VerticalScrollBar.Renderer = flatScrollBarRenderer2;
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnWrap);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnWrap);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedNormal.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Back, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.StartEditing);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.StartEditing);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke('='), FarPoint.Win.Spread.SpreadActions.StartEditingFormula);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.C, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.V, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardPasteAll);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.X, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCut);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Insert, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Delete, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCut);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Insert, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardPasteAll);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F4, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ShowSubEditor);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Space, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.SelectRow);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Z, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Undo);
            fpSpread1_InputMapWhenFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Y, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Redo);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenFocused, FarPoint.Win.Spread.OperationMode.Normal, fpSpread1_InputMapWhenFocusedNormal);
            fpSpread1_InputMapWhenFocusedReadOnly.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenFocusedReadOnly.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnWrap);
            fpSpread1_InputMapWhenFocusedReadOnly.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnWrap);
            fpSpread1_InputMapWhenFocusedReadOnly.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.C, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Insert, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Z, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Undo);
            fpSpread1_InputMapWhenFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Y, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Redo);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenFocused, FarPoint.Win.Spread.OperationMode.ReadOnly, fpSpread1_InputMapWhenFocusedReadOnly);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.None);
            fpSpread1_InputMapWhenFocusedRowMode.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.StartEditing);
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke('='), FarPoint.Win.Spread.SpreadActions.StartEditingFormula);
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ComboShowList);
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ComboShowList);
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F4, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ShowSubEditor);
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Z, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Undo);
            fpSpread1_InputMapWhenFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Y, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Redo);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenFocused, FarPoint.Win.Spread.OperationMode.RowMode, fpSpread1_InputMapWhenFocusedRowMode);
            fpSpread1_InputMapWhenFocusedSingleSelect.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenFocusedSingleSelect.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.C, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Insert, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Z, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Undo);
            fpSpread1_InputMapWhenFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Y, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Redo);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenFocused, FarPoint.Win.Spread.OperationMode.SingleSelect, fpSpread1_InputMapWhenFocusedSingleSelect);
            fpSpread1_InputMapWhenFocusedMultiSelect.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenFocusedMultiSelect.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.C, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Insert, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Z, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Undo);
            fpSpread1_InputMapWhenFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Y, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Redo);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenFocused, FarPoint.Win.Spread.OperationMode.MultiSelect, fpSpread1_InputMapWhenFocusedMultiSelect);
            fpSpread1_InputMapWhenFocusedExtendedSelect.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenFocusedExtendedSelect.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.C, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Insert, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ClipboardCopy);
            fpSpread1_InputMapWhenFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Z, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Undo);
            fpSpread1_InputMapWhenFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Y, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.Redo);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenFocused, FarPoint.Win.Spread.OperationMode.ExtendedSelect, fpSpread1_InputMapWhenFocusedExtendedSelect);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToNextPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToFirstColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToLastColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToFirstCell);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToLastCell);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToFirstColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToLastColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToFirstCell);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToLastCell);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Space, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.SelectColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Space, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.SelectSheet);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Escape, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.CancelEditing);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.StopEditing);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.CSEStopEditing);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnWrap);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnWrap);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F2, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ClearCell);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Oemplus, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.AutoSum);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F3, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.DateTimeNow);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F4, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ShowSubEditor);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ComboShowList);
            fpSpread1_InputMapWhenAncestorOfFocusedNormal.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ComboShowList);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenAncestorOfFocused, FarPoint.Win.Spread.OperationMode.Normal, fpSpread1_InputMapWhenAncestorOfFocusedNormal);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnWrap);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnWrap);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToNextPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ScrollToNextPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToFirstColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToLastColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ScrollToFirstCell);
            fpSpread1_InputMapWhenAncestorOfFocusedReadOnly.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ScrollToLastCell);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenAncestorOfFocused, FarPoint.Win.Spread.OperationMode.ReadOnly, fpSpread1_InputMapWhenAncestorOfFocusedReadOnly);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousRow);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToNextRow);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextPageOfRows);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToNextPageOfColumns);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToFirstColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToLastColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToFirstCell);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToLastCell);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Escape, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.CancelEditing);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.StopEditing);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
                    | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.CSEStopEditing);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumnWrap);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Tab, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.MoveToPreviousColumnWrap);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F2, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ClearCell);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F3, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.DateTimeNow);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.F4, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ShowSubEditor);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ComboShowList);
            fpSpread1_InputMapWhenAncestorOfFocusedRowMode.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ComboShowList);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenAncestorOfFocused, FarPoint.Win.Spread.OperationMode.RowMode, fpSpread1_InputMapWhenAncestorOfFocusedRowMode);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectPreviousItem);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectNextItem);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectPreviousPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectNextPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectFirstItem);
            fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectLastItem);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenAncestorOfFocused, FarPoint.Win.Spread.OperationMode.SingleSelect, fpSpread1_InputMapWhenAncestorOfFocusedSingleSelect);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousItem);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextItem);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToPreviousPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToFirstItem);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToLastItem);
            fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Space, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ToggleItem);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenAncestorOfFocused, FarPoint.Win.Spread.OperationMode.MultiSelect, fpSpread1_InputMapWhenAncestorOfFocusedMultiSelect);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Return, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.MoveToNextColumn);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent = new FarPoint.Win.Spread.InputMap();
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectPreviousItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectNextItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Left, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToPreviousColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Right, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.ScrollToNextColumnVisual);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Up, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Down, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectPreviousPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectNextPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.PageUp, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToPreviousPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Next, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToNextPageOfItems);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectFirstItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, System.Windows.Forms.Keys.None), FarPoint.Win.Spread.SpreadActions.SelectLastItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.Home, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToFirstItem);
            fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect.Parent.Put(new FarPoint.Win.Spread.Keystroke(System.Windows.Forms.Keys.End, ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.None)))), FarPoint.Win.Spread.SpreadActions.ExtendToLastItem);
            this.fpSpread1.SetInputMap(FarPoint.Win.Spread.InputMapMode.WhenAncestorOfFocused, FarPoint.Win.Spread.OperationMode.ExtendedSelect, fpSpread1_InputMapWhenAncestorOfFocusedExtendedSelect);
            this.fpSpread1.SetViewportLeftColumn(0, 0, 5);
            this.fpSpread1.SetActiveViewport(0, 0, -1);
            // 
            // fpSpread1_Sheet1
            // 
            this.fpSpread1_Sheet1.Reset();
            this.fpSpread1_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.fpSpread1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.fpSpread1_Sheet1.ColumnCount = 9;
            this.fpSpread1_Sheet1.RowCount = 30;
            this.fpSpread1_Sheet1.Cells.Get(0, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(0, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(1, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(2, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(3, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(4, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(5, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(6, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(7, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(8, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(9, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(10, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(11, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(12, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(13, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(14, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(15, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(16, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(17, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(18, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(19, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(20, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(21, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(22, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(23, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(24, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(25, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(26, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(27, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(28, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 0).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 1).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 2).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 3).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 4).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 5).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 6).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 7).Border = complexBorder2;
            this.fpSpread1_Sheet1.Cells.Get(29, 8).Border = complexBorder2;
            this.fpSpread1_Sheet1.ColumnFooter.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.fpSpread1_Sheet1.ColumnFooter.DefaultStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.ColumnFooter.DefaultStyle.ForeColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.ColumnFooter.DefaultStyle.Locked = false;
            this.fpSpread1_Sheet1.ColumnFooterSheetCornerStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.ColumnFooterSheetCornerStyle.ForeColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.ColumnFooterSheetCornerStyle.Locked = false;
            this.fpSpread1_Sheet1.ColumnHeader.AutoText = FarPoint.Win.Spread.HeaderAutoText.Blank;
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "출고일자";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "운송사";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "차량번호";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "외주처";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "재공형태";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "운송량(KG)";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "운송비(원)";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "차량톤수";
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.ColumnHeader.Cells.Get(0, 8).Value = "Bigo";
            this.fpSpread1_Sheet1.ColumnHeader.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            this.fpSpread1_Sheet1.ColumnHeader.DefaultStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.ColumnHeader.DefaultStyle.Font = new System.Drawing.Font("굴림체", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.fpSpread1_Sheet1.ColumnHeader.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.fpSpread1_Sheet1.ColumnHeader.DefaultStyle.Locked = false;
            this.fpSpread1_Sheet1.ColumnHeader.Rows.Get(0).Height = 30F;
            this.fpSpread1_Sheet1.ColumnHeader.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153))))), System.Drawing.SystemColors.ControlLightLight, System.Drawing.SystemColors.ControlDark, 1);
            this.fpSpread1_Sheet1.Columns.Default.SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
            textCellType1.MaxLength = 60;
            this.fpSpread1_Sheet1.Columns.Get(0).CellType = textCellType1;
            this.fpSpread1_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(0).Label = "출고일자";
            this.fpSpread1_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(0).Width = 85F;
            textCellType2.MaxLength = 60;
            this.fpSpread1_Sheet1.Columns.Get(1).CellType = textCellType2;
            this.fpSpread1_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.fpSpread1_Sheet1.Columns.Get(1).Label = "운송사";
            this.fpSpread1_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(1).Width = 126F;
            this.fpSpread1_Sheet1.Columns.Get(2).CellType = textCellType2;
            this.fpSpread1_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.fpSpread1_Sheet1.Columns.Get(2).Label = "차량번호";
            this.fpSpread1_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(2).Width = 133F;
            this.fpSpread1_Sheet1.Columns.Get(3).CellType = textCellType2;
            this.fpSpread1_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.fpSpread1_Sheet1.Columns.Get(3).Label = "외주처";
            this.fpSpread1_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(3).Width = 148F;
            this.fpSpread1_Sheet1.Columns.Get(4).CellType = textCellType1;
            this.fpSpread1_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(4).Label = "재공형태";
            this.fpSpread1_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(4).Width = 38F;
            numberCellType1.DecimalPlaces = 0;
            numberCellType1.DecimalSeparator = ".";
            numberCellType1.MaximumValue = 99999999999999D;
            numberCellType1.MinimumValue = -100000000D;
            numberCellType1.Separator = ",";
            numberCellType1.ShowSeparator = true;
            this.fpSpread1_Sheet1.Columns.Get(5).CellType = numberCellType1;
            this.fpSpread1_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.fpSpread1_Sheet1.Columns.Get(5).Label = "운송량(KG)";
            this.fpSpread1_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Top;
            this.fpSpread1_Sheet1.Columns.Get(5).Width = 96F;
            this.fpSpread1_Sheet1.Columns.Get(6).CellType = numberCellType1;
            this.fpSpread1_Sheet1.Columns.Get(6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.fpSpread1_Sheet1.Columns.Get(6).Label = "운송비(원)";
            this.fpSpread1_Sheet1.Columns.Get(6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Top;
            this.fpSpread1_Sheet1.Columns.Get(6).Width = 103F;
            numberCellType2.DecimalPlaces = 0;
            numberCellType2.DecimalSeparator = ".";
            numberCellType2.MaximumValue = 99999999999999D;
            numberCellType2.MinimumValue = -100000000D;
            numberCellType2.Separator = ",";
            numberCellType2.ShowSeparator = true;
            this.fpSpread1_Sheet1.Columns.Get(7).CellType = numberCellType2;
            this.fpSpread1_Sheet1.Columns.Get(7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.fpSpread1_Sheet1.Columns.Get(7).Label = "차량톤수";
            this.fpSpread1_Sheet1.Columns.Get(7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(7).Width = 39F;
            this.fpSpread1_Sheet1.Columns.Get(8).CellType = textCellType2;
            this.fpSpread1_Sheet1.Columns.Get(8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.fpSpread1_Sheet1.Columns.Get(8).Label = "Bigo";
            this.fpSpread1_Sheet1.Columns.Get(8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.Columns.Get(8).Width = 201F;
            this.fpSpread1_Sheet1.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.fpSpread1_Sheet1.DefaultStyle.Border = complexBorder1;
            textCellType3.MaxLength = 60;
            this.fpSpread1_Sheet1.DefaultStyle.CellType = textCellType3;
            this.fpSpread1_Sheet1.DefaultStyle.Font = new System.Drawing.Font("굴림체", 9F);
            this.fpSpread1_Sheet1.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.fpSpread1_Sheet1.DefaultStyle.Locked = false;
            this.fpSpread1_Sheet1.DefaultStyle.Renderer = textCellType3;
            this.fpSpread1_Sheet1.FilterBar.DefaultStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.FilterBar.DefaultStyle.ForeColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.FilterBar.DefaultStyle.Locked = false;
            this.fpSpread1_Sheet1.FilterBarHeaderStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.FilterBarHeaderStyle.ForeColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.FilterBarHeaderStyle.Locked = false;
            this.fpSpread1_Sheet1.FrozenColumnCount = 5;
            this.fpSpread1_Sheet1.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153))))), System.Drawing.SystemColors.ControlLightLight, System.Drawing.SystemColors.ControlDark, 1);
            this.fpSpread1_Sheet1.Protect = false;
            this.fpSpread1_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.fpSpread1_Sheet1.RowHeader.Columns.Get(0).Width = 32F;
            this.fpSpread1_Sheet1.RowHeader.DefaultStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.RowHeader.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.fpSpread1_Sheet1.RowHeader.DefaultStyle.Locked = false;
            this.fpSpread1_Sheet1.SheetCornerStyle.BackColor = System.Drawing.Color.Empty;
            this.fpSpread1_Sheet1.SheetCornerStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.fpSpread1_Sheet1.SheetCornerStyle.Locked = false;
            this.fpSpread1_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.fpSpread1_Sheet1.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153))))), System.Drawing.SystemColors.ControlLightLight, System.Drawing.SystemColors.ControlDark, 1);
            this.fpSpread1_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1359, 751);
            this.Controls.Add(this.fpSpread1);
            this.Controls.Add(this.button1);
            this.Name = "Main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form2";
            ((System.ComponentModel.ISupportInitialize)(this.fpSpread1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.fpSpread1_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Button button1;
        private FarPoint.Win.Spread.FpSpread fpSpread1;
        private FarPoint.Win.Spread.SheetView fpSpread1_Sheet1;
    }
}